stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "first step"
    - echo "second step"

test-job:
  stage: test
  script:
    - echo "Testing Step"

deploy-job:
  stage: deploy
  script:
    - echo "Deploy Step"
